// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  activeLink: string;
  brand: string;
  brandLogo: string;
  menuLink: string;
  menuWrap: string;
  root: string;
  wrap: string;
}
export const cssExports: CssExports;
export default cssExports;
